name: ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu
#    permissions:
#      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends clang curl ca-certificates pkg-config python3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Rust fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:7.1-ubuntu
#    permissions:
#      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends clang curl ca-certificates pkg-config python3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustc, cargo

      - name: tests
        run: cargo test
